version: '3.7'

# Varnish 6 and 7 - https://hub.docker.com/_/varnish
services:
  varnish-cache:
    image: varnish:{{varnish_version}}
    restart: always
    volumes:
      - ./varnish/varnish_magento.vcl:/etc/varnish/default.vcl:ro
