volumes:
  mysql57_volume:
#    name: MySql57-Volume

services:
  mysql57:
    container_name: mysql57
    image: mysql:5.7
    restart: always
    labels:
      - traefik.enable=false
#    network_mode: bridge
    ports:
      - 3357:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql57_volume:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf