version: '3.7'

volumes:
  elasticsearch_data:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - indices.query.bool.max_clause_count=10240
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw