<?php

namespace App\Command\Environment;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ValidateCommand extends \Symfony\Component\Console\Command\Command
{
    protected static $defaultName = 'environment:validate';

    protected function configure(): void
    {
        $this->setDescription('Validate environment to ensure Dockerizer can work as expected');

        parent::configure();
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
