version: '3.7'

#####
# Check for available PHP versions at https://hub.docker.com/r/defaultvalue/php/tags
#####

# ENV VARIABLES:
#   - SSL_CERTIFICATES_DIR: `~/misc/certs/` or other folder in the host system where SSL certificates are stored

services:
  php-apache:
    # Must be enclosed in double quotes, otherwise YAML is invalid
    container_name: "{{domains|first}}-{{environment}}"
    image: defaultvalue/php:{{php_version}}-production
    user: docker:docker
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: always

    # Must add extra_hosts to be written to /etc/hosts - otherwise containerized application can not curl itself
    extra_hosts:
      - "{{domains}}:127.0.0.1"
    environment:
      - COMPOSER_VERSION={{composer_version}}
    volumes:
      - .:/var/www/html
      - ${SSL_CERTIFICATES_DIR}:/certs
      - ./apache/virtual-host.conf:/etc/apache2/sites-enabled/virtual-host-{{environment}}.conf
      - test:test
      - test/file_1.txt:file_1.txt