version: '3.7'

volumes:
  mysql56_data:

services:
  mysql:
    container_name: mysql56
    image: mysql:5.6
    restart: always
    volumes:
      - mysql56_data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf